name: Unit Test

on:
  pull_request:
    branches:
      - main

jobs:
  test:
    runs-on: ubuntu-latest
    name: test
    timeout-minutes: 30
    steps:
      - uses: actions/checkout@v3
      - name: Install Poetry
        run: pipx install poetry==1.7.1
      - uses: actions/setup-python@v4
        with:
          python-version: "3.11"
          cache: "poetry"
      - name: Install Dependencies
        run: |
          poetry env use 3.11
          poetry install --no-interaction --no-ansi --no-root
      - name: Test
        run: |
          source $(poetry env info --path)/bin/activate
          coverage run
      - name: Coverage Report
        run: |
          source $(poetry env info --path)/bin/activate
          coverage report
      - name: HTML Report
        run: |
          source $(poetry env info --path)/bin/activate
          coverage html
      - name: Save HTML Report
        uses: actions/upload-artifact@v3
        with:
          name: htmlcov
          path: ./htmlcov/
          retention-days: 3
